# Generated by Django 5.2.4 on 2025-08-04 09:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("self_explanation", "0001_initial"),
        ("training_config", "0003_hyperparametersearch_searchtrial_trainingrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetExplanation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "explanation_text",
                    models.TextField(
                        help_text="The full, detailed self-explanation text for the dataset."
                    ),
                ),
                (
                    "key_findings",
                    models.JSONField(
                        default=list,
                        help_text="Bulleted list of key insights about the dataset.",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence in the explanation's analysis (0.0 to 1.0).",
                    ),
                ),
                (
                    "potential_biases",
                    models.TextField(
                        blank=True,
                        help_text="Potential biases or limitations of the dataset.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explanation",
                        to="training_config.datasetprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dataset Explanations",
                "ordering": ["-created_at"],
            },
        ),
    ]
