# Generated by Django 5.2.4 on 2025-08-04 02:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "training_config",
            "0002_cloudprovider_cloudtrainingjob_trainingnotebook_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HyperparameterSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "search_space",
                    models.JSONField(help_text="Optuna search space definition"),
                ),
                (
                    "n_trials",
                    models.PositiveIntegerField(
                        default=50, help_text="Number of trials to run"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("minimize", "Minimize"), ("maximize", "Maximize")],
                        default="minimize",
                        max_length=10,
                    ),
                ),
                (
                    "objective_metric",
                    models.CharField(default="validation_loss", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "base_configuration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training_config.trainingconfiguration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchTrial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("trial_number", models.IntegerField()),
                (
                    "params",
                    models.JSONField(help_text="Parameters suggested for this trial"),
                ),
                (
                    "value",
                    models.FloatField(
                        blank=True, help_text="Objective value", null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETE", "Complete"),
                            ("PRUNED", "Pruned"),
                            ("FAIL", "Fail"),
                        ],
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trials",
                        to="training_config.hyperparametersearch",
                    ),
                ),
            ],
            options={
                "ordering": ["search", "trial_number"],
            },
        ),
        migrations.CreateModel(
            name="TrainingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "training_logs",
                    models.JSONField(
                        default=dict, help_text="Training loss per step/epoch"
                    ),
                ),
                (
                    "validation_logs",
                    models.JSONField(
                        default=dict, help_text="Validation metrics per evaluation"
                    ),
                ),
                ("best_val_loss", models.FloatField(blank=True, null=True)),
                ("convergence_epoch", models.IntegerField(blank=True, null=True)),
                ("total_steps", models.IntegerField(blank=True, null=True)),
                (
                    "model_path",
                    models.CharField(
                        blank=True, help_text="Path to saved model", max_length=500
                    ),
                ),
                (
                    "report_path",
                    models.CharField(
                        blank=True, help_text="Path to generated report", max_length=500
                    ),
                ),
                ("performance_notes", models.TextField(blank=True)),
                (
                    "recommendations",
                    models.JSONField(
                        default=list, help_text="Automated recommendations"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training_config.trainingconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
