# Generated by Django 5.2.4 on 2025-08-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchproject",
            name="keywords",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="objectives",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="results",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
